# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('status', models.CharField(default='PROPOSED', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('applicant_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_projects', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apn', models.CharField(blank=True, help_text="Assessor's Parcel Number", max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(default='Santa Rosa', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project')),
            ],
        ),
    ]
