# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(default='HEARING', max_length=100)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('office_name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('term_length_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position_title', models.CharField(blank=True, max_length=200)),
                ('appointer_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_appointments', to='entities.entity')),
                ('body_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_appointments', to='entities.entity')),
                ('person_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('body_name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_profile', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('agenda_item', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=255)),
                ('vote_cast', models.CharField(choices=[('AYE', 'Aye / Yes'), ('NO', 'No'), ('ABSTAIN', 'Abstain'), ('RECUSED', 'Recused'), ('ABSENT', 'Absent')], max_length=20)),
                ('outcome', models.CharField(blank=True, help_text='e.g. Motion Passed 4-1', max_length=100)),
                ('governing_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_taken', to='government.governmentbody')),
                ('voter_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='entities.entity')),
            ],
        ),
    ]
