# Generated by Django 6.0.6 on 2026-07-01 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_migrate_existing_statuses'),
        ('government', '0001_initial'),
        ('sources', '0002_source_filing_date_source_updated_at_sourcelocator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('agenda_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_agendized', to='sources.source')),
                ('government_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='government.governmentbody')),
                ('minutes_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_minuted', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('staff_recommendation', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='entities.entity')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='government.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_text', models.TextField()),
                ('result', models.CharField(blank=True, max_length=100)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='government.agendaitem')),
                ('mover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions_moved', to='entities.entity')),
                ('seconder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motions_seconded', to='entities.entity')),
            ],
        ),
    ]
