# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('measure_letter', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('election_date', models.DateField()),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('election_year', models.IntegerField()),
                ('office_sought', models.CharField(blank=True, max_length=200)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_profile', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('fppc_id', models.CharField(blank=True, db_index=True, help_text='California FPPC ID number', max_length=50)),
                ('committee_name', models.CharField(max_length=255)),
                ('treasurer_name', models.CharField(blank=True, max_length=200)),
                ('candidate_or_measure', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to='entities.entity')),
            ],
        ),
    ]
