# Generated by Django 6.0.6 on 2026-07-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('entities', '0003_publicoffice_alias_source_locator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotmeasure',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballot_measure_profile', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='ballotmeasure',
            name='measure_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ballotmeasure',
            name='result',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_candidate', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_funded', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election_cycle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_for_office', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='committee',
            name='controlling_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_controlled', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='committee',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committees_sponsored', to='entities.entity'),
        ),
    ]
