# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('predicate', models.CharField(db_index=True, help_text='e.g., principal_of, contributed_to, employee_of', max_length=100)),
                ('object_value', models.CharField(blank=True, help_text='Literal value if object is not an entity', max_length=255)),
                ('claim_type', models.CharField(choices=[('FACTUAL', 'Factual Assertion'), ('INTERPRETIVE', 'Analytic Interpretation'), ('ALLEGATION', 'Allegation'), ('HYPOTHESIS', 'Research Hypothesis'), ('CONTEXT', 'Historical Context')], default='FACTUAL', max_length=30)),
                ('verification_status', models.CharField(choices=[('LEAD', 'Lead / Unverified'), ('UNVERIFIED', 'Unverified'), ('PARTIALLY_VERIFIED', 'Partially Verified'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('SUPERSEDED', 'Superseded'), ('RETRACTED', 'Retracted')], default='UNVERIFIED', max_length=30)),
                ('confidence_score', models.FloatField(default=100.0)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('sensitive_claim', models.BooleanField(default=False)),
                ('publication_status', models.CharField(choices=[('INTERNAL_ONLY', 'Internal Only'), ('NEEDS_REVIEW', 'Needs Review'), ('PUBLISHABLE', 'Publishable'), ('PUBLISHED', 'Published'), ('WITHHELD', 'Withheld')], default='INTERNAL_ONLY', max_length=30)),
                ('explanatory_note', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_assertions', to='entities.entity')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assertions', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='AssertionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('PRIMARY', 'Primary Direct Support'), ('CORROBORATING', 'Corroborating Support'), ('CONTRADICTING', 'Contradicting Evidence'), ('CONTEXTUAL', 'Contextual Background')], default='PRIMARY', max_length=30)),
                ('locator_text', models.CharField(blank=True, help_text='Page number, paragraph, or section reference', max_length=255)),
                ('concise_evidence_note', models.TextField(blank=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='assertions.assertion')),
                ('document_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentpage')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions_supported', to='sources.source')),
            ],
        ),
    ]
