# Generated by Django 6.0.6 on 2026-07-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assertions', '0001_initial'),
        ('sources', '0002_source_filing_date_source_updated_at_sourcelocator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredicateVocabulary',
            fields=[
                ('predicate_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(default='Directed', max_length=50)),
                ('definition', models.TextField(blank=True)),
                ('inverse_predicate', models.CharField(blank=True, max_length=100)),
                ('requires_object_entity', models.BooleanField(default=True)),
                ('allows_object_value', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sensitive_claim', models.BooleanField(default=False)),
                ('auto_generatable', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=True)),
                ('domain_entity_type', models.CharField(blank=True, max_length=50)),
                ('range_entity_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='assertion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assertions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assertion',
            name='interpretation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assertion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assertions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assertionsource',
            name='evidence_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assertionsource',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assertion_sources_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assertionsource',
            name='source_locator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assertion_sources', to='sources.sourcelocator'),
        ),
        migrations.AddField(
            model_name='assertionsource',
            name='source_quality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assertion',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assertions_reviewed_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assertion',
            name='verification_status',
            field=models.CharField(choices=[('LEAD', 'Lead / Unverified'), ('UNVERIFIED', 'Unverified'), ('PARTIALLY_VERIFIED', 'Partially Verified'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('SUPERSEDED', 'Superseded'), ('RETRACTED', 'Retracted'), ('ARCHIVED', 'Archived')], default='UNVERIFIED', max_length=30),
        ),
    ]
