# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='FORM_460_PARSER', max_length=50)),
                ('processing_engine', models.CharField(default='PyMuPDF+Regex', max_length=100)),
                ('engine_version', models.CharField(default='1.0', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('logs', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(help_text='e.g., committee_name, donor_name, contribution_amount', max_length=100)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_proposed_value', models.TextField(blank=True)),
                ('bounding_box_json', models.JSONField(blank=True, help_text='[x0, y0, x1, y1]', null=True)),
                ('confidence_score', models.FloatField(default=100.0)),
                ('reviewer_status', models.CharField(choices=[('PROPOSED', 'Proposed / Machine Extracted'), ('APPROVED', 'Approved by Reviewer'), ('CORRECTED', 'Corrected by Reviewer'), ('REJECTED', 'Rejected'), ('ILLEGIBLE', 'Illegible Field')], default='PROPOSED', max_length=30)),
                ('reviewer_correction', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_canonical_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_extracted_fields', to='entities.entity')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='documents.documentpage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='extraction.extractionjob')),
            ],
        ),
    ]
