# Generated by Django 6.0.6 on 2026-07-01 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0002_alter_entity_status_entitymerge'),
        ('extraction', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMatchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_method', models.CharField(max_length=50)),
                ('match_score', models.FloatField(default=0.0)),
                ('name_score', models.FloatField(default=0.0)),
                ('location_score', models.FloatField(default=0.0)),
                ('employer_score', models.FloatField(default=0.0)),
                ('entity_type_compatibility', models.BooleanField(default=True)),
                ('committee_id_match', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('model_version', models.CharField(default='2.0', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_attempts', to='transactions.contribution')),
                ('selected_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_attempts', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('match_method', models.CharField(blank=True, max_length=50)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity')),
                ('match_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='extraction.entitymatchattempt')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedContributorBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('raw_text', models.TextField()),
                ('bounding_box_json', models.JSONField(blank=True, help_text='[vx0, vy0, vx1, vy1]', null=True)),
                ('extraction_method', models.CharField(default='embedded_text_layout', max_length=50)),
                ('parser_version', models.CharField(default='2.0', max_length=50)),
                ('original_parsed_json', models.JSONField(default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_blocks', to='documents.documentpage')),
            ],
        ),
    ]
