# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='documents/%Y/%m/')),
                ('media_type', models.CharField(default='application/pdf', max_length=100)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.IntegerField(default=0)),
                ('has_native_text', models.BooleanField(default=False)),
                ('ocr_applied', models.BooleanField(default=False)),
                ('ocr_provider', models.CharField(blank=True, default='Tesseract', max_length=50)),
                ('ocr_version', models.CharField(blank=True, max_length=50)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('HASHING', 'Hashing'), ('QUEUED', 'Queued for Extraction'), ('EXTRACTING', 'Extracting Text'), ('OCR_COMPLETE', 'OCR Complete'), ('EXTRACTION_COMPLETE', 'Extraction Complete'), ('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('FAILED', 'Processing Failed')], default='UPLOADED', max_length=30)),
                ('original_preserved', models.BooleanField(default=True, editable=False)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sources.source')),
                ('upload_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(blank=True, help_text='Average OCR confidence score 0-100', null=True)),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='page_images/%Y/%m/')),
                ('processing_status', models.CharField(default='EXTRACTED', max_length=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
