# Generated by Django 6.0.6 on 2026-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='publication_classification',
            field=models.CharField(default='PUBLIC', max_length=50),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='page_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='page_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='review_status',
            field=models.CharField(default='UNREVIEWED', max_length=30),
        ),
    ]
