# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('canonical_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed / In Intake'), ('APPROVED', 'Approved Canonical Entity'), ('MERGED', 'Merged into another entity'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('publication_status', models.CharField(choices=[('INTERNAL_ONLY', 'Internal Only'), ('NEEDS_REVIEW', 'Needs Review'), ('PUBLISHABLE', 'Publishable'), ('PUBLISHED', 'Published'), ('WITHHELD', 'Withheld')], default='INTERNAL_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organization_profile', serialize=False, to='entities.entity')),
                ('org_category', models.CharField(choices=[('CAMPAIGN_COMMITTEE', 'Campaign Committee'), ('DEVELOPER_CORP', 'Development Corporation'), ('GOVT_AGENCY', 'Government Agency'), ('LOBBYING_FIRM', 'Lobbying / Public Affairs Firm'), ('NON_PROFIT', 'Non-Profit / Advocacy Group'), ('OTHER', 'Other Organization')], default='OTHER', max_length=50)),
                ('legal_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('formation_date', models.DateField(blank=True, null=True)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('committee_id', models.CharField(blank=True, db_index=True, help_text='State FPPC or FEC ID', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person_profile', serialize=False, to='entities.entity')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('public_role', models.CharField(blank=True, max_length=200)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(db_index=True, max_length=255)),
                ('alias_type', models.CharField(default='ALT_NAME', max_length=50)),
                ('normalized_alias', models.CharField(db_index=True, max_length=255)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('review_status', models.CharField(default='APPROVED', max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='entities.entity')),
            ],
        ),
    ]
