# Generated by Django 6.0.6 on 2026-07-01 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('PROVISIONAL_AUTO_CREATED', 'Provisional Auto Created'), ('AUTO_MATCHED', 'Auto Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('MERGED', 'Merged into another entity'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived'), ('PROPOSED', 'Proposed / In Intake'), ('APPROVED', 'Approved Canonical Entity')], default='APPROVED', max_length=50),
        ),
        migrations.CreateModel(
            name='EntityMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('reversible', models.BooleanField(default=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_out', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merges_in', to='entities.entity')),
            ],
        ),
    ]
