# Generated by Django 6.0.6 on 2026-07-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_entity_status_entitymerge'),
        ('sources', '0002_source_filing_date_source_updated_at_sourcelocator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicOffice',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='public_office_profile', serialize=False, to='entities.entity')),
                ('office_name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('elected_or_appointed', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='source_locator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='sources.sourcelocator'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization'), ('CAMPAIGN', 'Campaign'), ('COMMITTEE', 'Committee'), ('BALLOT_MEASURE', 'Ballot Measure'), ('DEVELOPMENT_PROJECT', 'Development Project'), ('GOVERNMENT_BODY', 'Government Body'), ('PUBLIC_OFFICE', 'Public Office'), ('PROPERTY_OR_SITE', 'Property or Site'), ('CONTRACT', 'Contract'), ('EVENT', 'Event'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('PROVISIONAL_AUTO_CREATED', 'Provisional Auto Created'), ('AUTO_MATCHED', 'Auto Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed'), ('MERGED', 'Merged into another entity'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived'), ('PROPOSED', 'Proposed / In Intake'), ('APPROVED', 'Approved Canonical Entity')], default='APPROVED', max_length=50),
        ),
        migrations.CreateModel(
            name='GovernmentBody',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='government_body_profile', serialize=False, to='entities.entity')),
                ('body_type', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('parent_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_bodies', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project_profile', serialize=False, to='entities.entity')),
                ('project_category', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_applied', to='entities.entity')),
                ('property_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_owned', to='entities.entity')),
            ],
        ),
    ]
