# Generated by Django 6.0.6 on 2026-07-01 07:06

from django.db import migrations

def map_statuses(apps, schema_editor):
    Entity = apps.get_model('entities', 'Entity')
    Contribution = apps.get_model('transactions', 'Contribution')
    
    # Update Entities
    for ent in Entity.objects.all():
        if ent.status == 'PROPOSED':
            ent.status = 'PROVISIONAL_AUTO_CREATED'
            ent.save()
        elif ent.status == 'APPROVED':
            ent.status = 'VERIFIED'
            ent.save()
            
    # Update Contributions
    for con in Contribution.objects.all():
        if con.review_status == 'PROPOSED':
            con.review_status = 'AUTO_IMPORTED'
            con.save()
        elif con.review_status in ('APPROVED', 'CORRECTED'):
            con.review_status = 'VERIFIED'
            con.save()

class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_publicoffice_alias_source_locator_and_more'),
        ('transactions', '0002_contribution_document_contribution_extracted_block_and_more'),
    ]

    operations = [
        migrations.RunPython(map_statuses, reverse_code=migrations.RunPython.noop),
    ]
