# Generated by Django 6.0.6 on 2026-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_migrate_existing_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymerge',
            name='reassigned_relations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
