# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('contract_title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True)),
                ('agency_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_contracts', to='entities.entity')),
                ('vendor_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_contracts', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('donor_raw_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cumulative_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('schedule', models.CharField(default='Schedule A', max_length=50)),
                ('transaction_code', models.CharField(blank=True, help_text='IND, COM, OTH, PTY, SCC', max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('city_state_zip', models.CharField(blank=True, max_length=200)),
                ('source_locator', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('PROPOSED', 'Proposed / Machine Extracted'), ('APPROVED', 'Approved by Reviewer'), ('CORRECTED', 'Corrected by Reviewer'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=30)),
                ('document_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentpage')),
                ('donor_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_made', to='entities.entity')),
                ('filer_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_received', to='entities.entity')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('payee_raw_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.CharField(default='Schedule E', max_length=50)),
                ('transaction_code', models.CharField(blank=True, help_text='CMP, CNS, LIT, POS, PRO, PRT, RAD, SAL, TEL, TRV, VOT, WEB', max_length=50)),
                ('review_status', models.CharField(choices=[('PROPOSED', 'Proposed / Machine Extracted'), ('APPROVED', 'Approved by Reviewer'), ('CORRECTED', 'Corrected by Reviewer'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=30)),
                ('document_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentpage')),
                ('filer_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures_made', to='entities.entity')),
                ('payee_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures_received', to='entities.entity')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('borrower_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_received', to='entities.entity')),
                ('lender_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_given', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('reporting_period', models.CharField(blank=True, max_length=50)),
                ('compensation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('matters_described', models.TextField(blank=True)),
                ('agency_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobbying_targeted_agency', to='entities.entity')),
                ('client_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbying_as_client', to='entities.entity')),
                ('lobbyist_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbying_as_firm', to='entities.entity')),
            ],
        ),
    ]
