# Generated by Django 6.0.6 on 2026-07-01 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('documents', '0001_initial'),
        ('extraction', '0002_entitymatchattempt_entitymatchcandidate_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='extracted_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='extraction.extractedcontributorblock'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='audit.importbatch'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='match_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contributions', to='extraction.entitymatchattempt'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='review_status',
            field=models.CharField(choices=[('AUTO_IMPORTED', 'Auto Imported'), ('AUTO_MATCHED', 'Auto Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('SUPERSEDED', 'Superseded'), ('REJECTED', 'Rejected'), ('PROPOSED', 'Proposed / Machine Extracted'), ('APPROVED', 'Approved by Reviewer'), ('CORRECTED', 'Corrected by Reviewer')], default='AUTO_IMPORTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='review_status',
            field=models.CharField(choices=[('AUTO_IMPORTED', 'Auto Imported'), ('AUTO_MATCHED', 'Auto Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('REVIEWED', 'Reviewed'), ('VERIFIED', 'Verified'), ('SUPERSEDED', 'Superseded'), ('REJECTED', 'Rejected'), ('PROPOSED', 'Proposed / Machine Extracted'), ('APPROVED', 'Approved by Reviewer'), ('CORRECTED', 'Corrected by Reviewer')], default='PROPOSED', max_length=30),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('prior_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
