# Generated by Django 6.0.6 on 2026-07-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_legacyidentifier_entity_and_more'),
        ('transactions', '0002_contribution_document_contribution_extracted_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='agent_contractor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='amendment_status',
            field=models.CharField(default='ORIGINAL', max_length=50),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='candidate_measure',
            field=models.CharField(blank=True, help_text='Supported or opposed candidate/measure', max_length=255),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='extraction_status',
            field=models.CharField(default='SUCCESS', max_length=50),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='filing_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='filing_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='audit.importbatch'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='raw_extraction_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expenditures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='source_locator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='subcontractor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='transactions.expenditure'),
        ),
    ]
