# Generated by Django 6.0.6 on 2026-07-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_expenditure_agent_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='amendment_status',
            field=models.CharField(default='ORIGINAL', max_length=50),
        ),
        migrations.AddField(
            model_name='contribution',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='transactions.contribution'),
        ),
    ]
