# Generated by Django 6.0.6 on 2026-07-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_ballotmeasure_entity_ballotmeasure_measure_number_and_more'),
        ('transactions', '0004_contribution_amendment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='consultant_vendor_role',
            field=models.CharField(blank=True, help_text='e.g. CONSULTANT_TO, VENDOR_TO', max_length=100),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='source_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
