# Generated by Django 6.0.6 on 2026-07-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_expenditure_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='is_independent_expenditure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='support_oppose',
            field=models.CharField(blank=True, choices=[('SUPPORT', 'Support'), ('OPPOSE', 'Oppose')], max_length=10),
        ),
    ]
