# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('FORM_460', 'Form 460 Campaign Disclosure'), ('FORM_410', 'Form 410 Statement of Organization'), ('LOBBYING_DISCLOSURE', 'Lobbying Disclosure'), ('MEETING_MINUTES', 'Meeting Minutes'), ('STAFF_REPORT', 'Staff Report'), ('CONTRACT', 'Government Contract'), ('APPOINTMENT_RECORD', 'Appointment Record'), ('PRA_RESPONSE', 'Public Records Act Response'), ('NEWS_ARTICLE', 'News Article / Investigative Report'), ('OTHER', 'Other Documented Source')], default='OTHER', max_length=50)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('access_date', models.DateField(blank=True, null=True)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('archive_url', models.URLField(blank=True, max_length=500)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reliability', models.CharField(choices=[('OFFICIAL_PUBLIC_RECORD', 'Official Public Record'), ('VERIFIED_PRIMARY', 'Verified Primary Source'), ('CORROBORATED_SECONDARY', 'Corroborated Secondary Source'), ('UNVERIFIED_CLAIM', 'Unverified Claim / Lead')], default='OFFICIAL_PUBLIC_RECORD', max_length=50)),
                ('privacy_classification', models.CharField(choices=[('PUBLIC', 'Public Record'), ('INTERNAL', 'Internal Research'), ('RESTRICTED', 'Restricted / Sensitive')], default='PUBLIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
