# Generated by Django 6.0.6 on 2026-07-01 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_document_type_document_processing_version_and_more'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SourceLocator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_range', models.CharField(blank=True, max_length=50)),
                ('bounding_box_json', models.JSONField(blank=True, help_text='[vx0, vy0, vx1, vy1]', null=True)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('table_identifier', models.CharField(blank=True, max_length=100)),
                ('agenda_item', models.CharField(blank=True, max_length=50)),
                ('filing_schedule', models.CharField(blank=True, max_length=50)),
                ('locator_description', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locators', to='documents.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locators', to='documents.documentpage')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locators', to='sources.source')),
            ],
        ),
    ]
