# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('current_public_id', models.CharField(db_index=True, max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('migration_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('change_type', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('prior_value_summary', models.TextField(blank=True, null=True)),
                ('new_value_summary', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('source_file', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(default='IN_PROGRESS', max_length=50)),
                ('summary_counts', models.JSONField(default=dict)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet', models.CharField(max_length=100)),
                ('source_row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(default='IMPORTED', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='audit.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledVocabularyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deprecated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.controlledvocabularyvalue')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
    ]
