# Generated by Django 6.0.6 on 2026-07-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('entities', '0003_publicoffice_alias_source_locator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyidentifier',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_identifiers', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='legacyidentifier',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_identifiers', to='audit.importbatch'),
        ),
        migrations.AddField(
            model_name='legacyidentifier',
            name='originating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legacyidentifier',
            name='source_workbook',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
