# Generated by Django 6.0.6 on 2026-06-28 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('affected_object_type', models.CharField(max_length=100)),
                ('affected_object_id', models.CharField(max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title_description', models.CharField(max_length=255)),
                ('url_or_file', models.CharField(blank=True, max_length=500)),
                ('item_type', models.CharField(default='LEAD', max_length=50)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('processing_status', models.CharField(default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRARequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('target_agency', models.CharField(max_length=200)),
                ('request_summary', models.TextField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('repository', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(default='Sonoma County', max_length=100)),
                ('research_use', models.TextField(blank=True)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('access_notes', models.TextField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed_entities', to='entities.entity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_reviews', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(help_text='Fuzzy similarity score 0-100')),
                ('matching_fields', models.JSONField(default=list)),
                ('conflicting_fields', models.JSONField(default=list)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('entity_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_as_1', to='entities.entity')),
                ('entity_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_as_2', to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('related_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('task_title', models.CharField(max_length=255)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
