# Generated by Django 6.0.6 on 2026-07-01 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assertions', '0002_predicatevocabulary_assertion_created_by_and_more'),
        ('entities', '0004_migrate_existing_statuses'),
        ('research', '0001_initial'),
        ('sources', '0002_source_filing_date_source_updated_at_sourcelocator'),
        ('transactions', '0002_contribution_document_contribution_extracted_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertions', models.ManyToManyField(blank=True, related_name='research_collections', to='assertions.assertion')),
                ('contributions', models.ManyToManyField(blank=True, related_name='research_collections', to='transactions.contribution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_collections', to=settings.AUTH_USER_MODEL)),
                ('entities', models.ManyToManyField(blank=True, related_name='research_collections', to='entities.entity')),
                ('sources', models.ManyToManyField(blank=True, related_name='research_collections', to='sources.source')),
            ],
        ),
    ]
