# Generated by Django 6.0.6 on 2026-07-01 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('query_string', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
