# Generated by Django 6.0.6 on 2026-07-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='research.researchcollection'),
        ),
        migrations.AddField(
            model_name='prarequest',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pra_requests', to='research.researchcollection'),
        ),
        migrations.AddField(
            model_name='researchtask',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='research.researchcollection'),
        ),
    ]
